### ISSUE TITLE
Some libraries might help

### ISSUE THREAD

**Issue by songkeys** [GRP-17/feedback-frontend#1]
- [x] Create React apps with no build configuration: <https://github.com/facebook/create-react-app>
- [ ] ~~A simple React component capable of building HTML forms out of a JSON schema and using Bootstrap semantics by default: <https://github.com/mozilla-services/react-jsonschema-form>~~
- UI
  - [ ] <https://material-ui.com/> (following the Google standard)
  - [x] <https://ant.design/> **(I prefer this one)**
    - [ ] <https://pro.ant.design/> (ant design with common templates to use)
  - [ ] <https://onsen.io/> (native-like mobile UI)

**Comment by psyrr1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPR3: Feedback Component](https://trello.com/c/BrsqHiBo/21-spr3-feedback-component)
