### ISSUE TITLE
Dashboard: volumes

### ISSUE THREAD

**Issue by songkeys** [GRP-17/feedback-frontend#2]
Display the total number of ratings received, together with a daily average.
![image](https://user-images.githubusercontent.com/22665058/50617509-8b5df100-0ee5-11e9-87f2-90778973760f.png)

**Comment by songkeys** [comment]
https://github.com/GRP-17/feedback-frontend/commit/48598b14b881e581d1582669855145637552db71

**Comment by psyrr1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPR3: Dashboard: volumes](https://trello.com/c/JH6Ip0ep/19-spr3-dashboard-volumes)
