### ISSUE TITLE
[Discussion] Dashboard Layout Design

### ISSUE THREAD

**Issue by songkeys** [GRP-17/feedback-frontend#23]
We now have two versions of design:

# Left-Right

![left-right](https://user-images.githubusercontent.com/22665058/54076321-5897f680-42a2-11e9-9ece-1eb5efb167e3.png)

# Top-Down

![top-down](https://user-images.githubusercontent.com/22665058/54076316-4d44cb00-42a2-11e9-9b2b-3ffba0d6f0c8.png)

---

The display of feedback list is not determined yet. It could be multi-columns or a single column in both versions.

Note in the requirement:

> *"As a dashboard user I want the landing screen to load as quickly as possible. As the feedback database may contain a large number of reviews, only display the first 25 (the 25 most recently received) on page load.*
> 
> *Provide a means of navigating through the rest of the reviews, with pages returning 25 reviews."*
> 
> -- Tamas Gyorfi

(25 per page... So it has to be `1*25` or `5*5` to make layout reasonable..)

---

Or we could just simply follow the demo one Tamas provided:

![Capital One](https://user-images.githubusercontent.com/22665058/54076427-67cb7400-42a3-11e9-8815-5f525bb32dc9.png)

by putting the phrase item below together with a two-column feedback list.

**Comment by songkeys** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPR7: Dashboard: Design/Organise Layout](https://trello.com/c/erdgcVQs/34-spr7-dashboard-design-organise-layout)

**Comment by psyrr1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPR7: Produce prototype designs for Dashboard UI](https://trello.com/c/6x0K1BDJ/48-spr7-produce-prototype-designs-for-dashboard-ui)

**Comment by songkeys** [comment]
Initial implementation:
![image](https://user-images.githubusercontent.com/22665058/54356398-7030ff80-4653-11e9-9601-09df2041b719.png)
