### ISSUE TITLE
Dashboard: sentiment breakdown

### ISSUE THREAD

**Issue by songkeys** [GRP-17/feedback-frontend#4]
Display the frequency of different sentiments.
![image](https://user-images.githubusercontent.com/22665058/50617868-3a4efc80-0ee7-11e9-8a8b-6b1d370a7729.png)

**Comment by songkeys** [comment]
closed via https://github.com/GRP-17/feedback-frontend/commit/a95fad60e06e57151a86794cc9711537ba8c5184

**Comment by psyrr1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPR4: Dashboard: sentiment breakdown](https://trello.com/c/wQqIN7b9/15-spr4-dashboard-sentiment-breakdown)
