### ISSUE TITLE
Dashboard: star rating breakdown

### ISSUE THREAD

**Issue by songkeys** [GRP-17/feedback-frontend#5]
Display how many times was each star rating option selected.
![image](https://user-images.githubusercontent.com/22665058/50617899-60749c80-0ee7-11e9-91ac-04ecc497d255.png)

**Comment by songkeys** [comment]
https://github.com/GRP-17/feedback-frontend/commit/4bfa038a3941eb8a5c1da070e433a28c0426cbb8

**Comment by psyrr1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPR5: Dashboard: star rating breakdown](https://trello.com/c/9cYMKdx0/16-spr5-dashboard-star-rating-breakdown)
