### ISSUE TITLE
Dashboard: average rating

### ISSUE THREAD

**Issue by songkeys** [GRP-17/feedback-frontend#6]
Display the average rating in a 'x.x out of 5' format.
![image](https://user-images.githubusercontent.com/22665058/50617925-8437e280-0ee7-11e9-8935-a659fd1d9c76.png)

**Comment by psyrr1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPR5: Dashboard: average rating](https://trello.com/c/toixI9CL/17-spr5-dashboard-average-rating)
