### ISSUE TITLE
Dashboard: feedback received

### ISSUE THREAD

**Issue by songkeys** [GRP-17/feedback-frontend#8]
Display the last 10 pieces of feedback on the dashboard. See the picture attached (Optional: if you'd like to capture names, that's fine. However, names should never be mandatory).

- It is not required to implement paging atm. Show the latest 10 ratings.
- All ratings shown should have a sentiment indication: red for negative, white for neutral and green for positive.
- The star rating should be displayed with the feedback.
- If there is no free text feedback received, display: 'No feedback' in italic
- If the feedback text is too long, it should be scrollable. The ratings displayed should have the same height and width
- The date of the feedback received to be displayed
![image](https://user-images.githubusercontent.com/22665058/50617953-b1849080-0ee7-11e9-89db-9f276fb1e3e4.png)

**Comment by psyrr1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SPR5: Dashboard: feedback received](https://trello.com/c/eQhIvSv5/20-spr5-dashboard-feedback-received)
